# Site settings
title: "William Box - Game Programmer"
email: "william@wpbox.dev"
description: "Game Programmer & AI Developer Portfolio"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wpbox.dev" # your custom domain

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"